#!/bin/bash

# cleanup
echo "## CLEANING UP (IGNORE) ##"
docker rmi --force $(docker images -f "dangling=true" -q)
docker rm $(docker ps -a -f status=exited -f status=created -q)

# force recreate
echo "## REBUILD IMAGE AND RESTARTING ##"
docker-compose build --no-cache --build-arg REBOOT_ID=$1

# (will be exited at this point, so restart it)
docker container create --name rubber_duck_$1 -v /var/run/docker.sock:/var/run/docker.sock:ro --env-file .env rubber_duck-bot
docker container start rubber_duck_$1

docker container stop $(hostname)